#!/bin/sh

set -e

if [ -e /usr/lib/libcuteradio.so ]
    then
        rm /usr/lib/libcuteradio.so
fi

if [ -e /usr/lib/libcuteradio.so.1 ]
    then
        rm /usr/lib/libcuteradio.so.1
fi

if [ -e /usr/lib/libcuteradio.so.1.0 ]
    then
        rm /usr/lib/libcuteradio.so.1.0
fi

if [ -e /usr/lib/libcuteradio.so.1.0.0 ]
    then
        rm /usr/lib/libcuteradio.so.1.0.0
fi

if [ -h /usr/lib/qt4/imports/CuteRadio ]
    then
        rm /usr/lib/qt4/imports/CuteRadio
fi

exit 0
